name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: base64-to-file
        uses: timheuer/base64-to-file@v1.0.3
        with:
          # Name of the file when written to temp location
          fileName: quotey.jks
          # The base64 encoded string
          encodedString: ${{ secrets.KEY_JKS }}
          working-directory: ./app
      - name: Fastlane Action
        uses: maierj/fastlane-action@v1.4.0
        with:
          lane: deploy
        env:
          SERIVCE_ACCOUNT_JSON: ${{ secrets.SERIVCE_ACCOUNT_JSON }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_ALIAS_PASSWORD: ${{ secrets.KEY_ALIAS_PASSWORD }}
